# Inspired by https://simonwillison.net/2020/Oct/9/git-scraping/

name: Fetches Chromium netlog events header

# Controls when the workflow will run
on:
#  push:
  workflow_dispatch:
#  schedule:
#    - cron:  '0 5 * * *'

jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Update deps
        run: |
          sudo apt-get update -y
        
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Fetch Chromium source files
        run: |-
          mkdir -p source/main/net/log
          curl "https://chromium.googlesource.com/chromium/src/+/main/net/log/net_log_event_type_list.h?format=TEXT" | base64 -d > source/main/net/log/net_log_event_type_list.h

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Updated: ${timestamp}" || exit 0
          git push
